create table
  public.users (
    user_id bigint generated by default as identity,
    name text null,
    email text null,
    age integer null,
    created_at timestamp with time zone not null default now(),
    constraint users_pkey primary key (user_id),
    constraint users_user_id_key unique (user_id)
  ) tablespace pg_default;

create table
  public.routes (
    route_id bigint generated by default as identity,
    yds text null,
    trad boolean null default false,
    sport boolean null default false,
    description text null,
    location text null,
    protection text null,
    created_at timestamp with time zone not null default now(),
    route_name text null,
    route_lat text null,
    route_lon text null,
    other boolean null default false,
    state_name text null,
    constraint routes_pkey primary key (route_id),
    constraint routes_route_id_key unique (route_id)
  ) tablespace pg_default;

create index if not exists max_yds_idx on public.routes using btree (yds) tablespace pg_default;

create table
  public.climbing (
    climbing_id bigint generated by default as identity,
    user_id bigint null,
    frequency integer null,
    intensity integer null,
    route_id bigint null,
    heart_rate integer null,
    systolic_pressure integer null,
    diastolic_pressure integer null,
    created_at timestamp with time zone not null default now(),
    constraint climbing_pkey primary key (climbing_id),
    constraint climbing_route_id_fkey foreign key (route_id) references routes (route_id) on update cascade on delete cascade,
    constraint climbing_user_id_fkey foreign key (user_id) references users (user_id) on update cascade on delete cascade
  ) tablespace pg_default;

create table
  public.ratings (
    user_id bigint not null,
    route_id bigint not null,
    rating real null,
    created_at timestamp with time zone null,
    rating_id bigint generated by default as identity,
    constraint ratings_pkey primary key (rating_id),
    constraint ratings_route_id_fkey foreign key (route_id) references routes (route_id) on update cascade on delete cascade,
    constraint ratings_user_id_fkey foreign key (user_id) references users (user_id) on update cascade on delete cascade
  ) tablespace pg_default;