create table
  public.users (
    user_id bigint generated by default as identity,
    name text null,
    email text null,
    age integer null,
    created_at timestamp with time zone not null default now(),
    constraint users_pkey primary key (user_id)
  ) tablespace pg_default;

create table
  public.routes (
    route_id bigint generated by default as identity,
    "YDS" text null,
    "Font" text null,
    "French" text null,
    "Ewbanks" text null,
    "UIAA" text null,
    "ZA" text null,
    "British" text null,
    yds_aid text null,
    boulder boolean null default false,
    tr boolean null default false,
    ice boolean null default false,
    trad boolean null default false,
    sport boolean null default false,
    aid boolean null default false,
    mixed boolean null default false,
    snow boolean null default false,
    alpine boolean null default false,
    fa text null,
    description text null,
    location text null,
    protection text null,
    created_at timestamp with time zone not null default now(),
    route_name text null,
    constraint routes_pkey primary key (route_id)
  ) tablespace pg_default;


create table
  public.ratings (
    user_id bigint not null,
    route_id bigint not null,
    rating real null,
    created_at timestamp with time zone null,
    rating_id bigint not null,
    constraint ratings_pkey primary key (rating_id),
    constraint ratings_route_id_fkey foreign key (route_id) references routes (route_id) on update cascade on delete cascade,
    constraint ratings_user_id_fkey foreign key (user_id) references users (user_id) on update cascade on delete cascade
  ) tablespace pg_default;


create table
  public.climbing (
    climbing_id bigint generated by default as identity,
    user_id bigint null,
    frequency integer null,
    intensity integer null,
    route_id bigint null,
    heart_rate integer null,
    systolic_pressure integer null,
    diastolic_pressure integer null,
    created_at timestamp with time zone not null default now(),
    constraint climbing_pkey primary key (climbing_id),
    constraint climbing_route_id_fkey foreign key (route_id) references routes (route_id) on update cascade on delete cascade,
    constraint climbing_user_id_fkey foreign key (user_id) references users (user_id) on update cascade on delete cascade
  ) tablespace pg_default;