create table
  public.routes (
    route_id bigint generated by default as identity,
    name text null,
    location text null,
    difficulty_level text null,
    style text null,
    created_at timestamp with time zone not null default now(),
    constraint routes_pkey primary key (route_id)
  ) tablespace pg_default;

create table
  public.profile (
    profile_id bigint generated by default as identity,
    name text null,
    email text null,
    age integer null,
    created_at timestamp with time zone not null default now(),
    constraint profile_pkey primary key (profile_id)
  ) tablespace pg_default;

create table
  public.climbing (
    climb_id bigint generated by default as identity,
    profile_id bigint null,
    route_id integer null,
    frequency integer null,
    intensity integer null,
    heart_rate integer null,
    systolic_pressure integer null,
    diastolic_pressure integer null,
    created_at timestamp with time zone not null default now(),
    constraint climbing_pkey primary key (climb_id),
    constraint climbing_profile_id_fkey foreign key (profile_id) references profile (profile_id) on update cascade on delete cascade,
    constraint climbing_route_id_fkey foreign key (route_id) references routes (route_id) on update cascade on delete cascade
  ) tablespace pg_default;